#!/usr/bin/env bash 
set -x 

sudo apt-get install -y -qq qtbase5-dev libsdl2-ttf-dev 

LAUNCHER_PATH="/home/$P_USERNAME/Desktop/CoCoMAME.desktop"
WEB_URL_PATH="/home/$P_USERNAME/Desktop/FujiNet-CoCo-WebUI.desktop"
CODE_PATH="${P_FN_PATH}/CoCoMAME"
mkdir -p "$CODE_PATH/cfg" 
cd "$CODE_PATH" || exit
tar -zxvf /tmp/cocomame.tar.gz && rm /tmp/cocomame.tar.gz

cat <<EOF > "$CODE_PATH/cfg/coco2b.cfg"
<?xml version="1.0"?>
<!-- This is autogenerated; comments and unknown tags will be stripped -->
<mameconfig version="10">
  <system name="coco2b">
    <input>
      <port tag=":beckerport" type="CONFIG" mask="1" defvalue="0" value="1" />
    </input>
  </system>
</mameconfig>
EOF

cat <<EOF > "$LAUNCHER_PATH"
[Desktop Entry]
Encoding=UTF-8
Name=FujiNet CoCo MAME
Comment=FujiNet connected to CoCo MAME
Type=Application
Exec=$CODE_PATH/cocomame coco2b -window -ext fdc,bios=hdbk3 -skip_gameinfo
Path=$CODE_PATH
Icon=org.xfce.settings.color
EOF

chmod +x "$LAUNCHER_PATH"
gio set -t string "$LAUNCHER_PATH" metadata::xfce-exe-checksum "$(sha256sum "$LAUNCHER_PATH" | awk '{print $1}')"

cat <<EOF > "$WEB_URL_PATH"
[Desktop Entry]
Version=1.0
Name=FujiNet CoCo Web UI
Comment=Web UI admin console for FujiNet CoCo
Type=Link
Icon=/home/$P_USERNAME/Pictures/fn-logo-black.png
URL=http://localhost:8002
EOF

chmod +x "$WEB_URL_PATH"
gio set -t string "$WEB_URL_PATH" metadata::xfce-exe-checksum "$(sha256sum "$WEB_URL_PATH" | awk '{print $1}')"