#!/usr/bin/env bash

YELLOW="\e[1;33m"
BLUE="\e[1;36m"
GRAY="\e[37m"
DKBLUE_BACK="\e[44m"
NOCOLOR="\e[0m"

MY_IP="$(ip addr | grep -A1 "ether" | awk '/inet/ {print $2}' | sed 's#/24##')"

clear
echo -e "${GRAY}"
figlet -f mini -ck "Local IP address:"
echo -e "${YELLOW}"
figlet -f banner -c "$MY_IP"
echo -e "${NOCOLOR}"

echo -e "${GRAY}Connect to netcat with the following code in Altirra:"
echo -e "${BLUE}${DKBLUE_BACK}"
echo -e "\tOPEN #1,12,2,\"N:TCP://$MY_IP:6502/\""
echo -e "\tPRINT #1;\"HELLO FROM ATARI #x\""
echo -e "${NOCOLOR}${GRAY}"
echo -e "Running command ${BLUE}nc -l -p 6502${NOCOLOR}${GRAY} ... "
echo -e "${GRAY}Sent from the Atari:${NOCOLOR}"
echo -e "${YELLOW}"
netcat -l -p 6502
