#!/usr/bin/env bash 
#set -x

#ALTIRRA_URL="https://virtualdub.org/downloads/Altirra-4.20.zip"
FUJINET_ROOT="$HOME/FujiNet"

RED="\033[31m"
YELLOW="\033[1;33m"
GREEN="\033[32m"
BLUE="\033[1;34m"
DARK_GRAY="\033[1;30m"
NOCOLOR="\033[0m"

function usage() {
  echo -e "${YELLOW}upgrade_vm ${DARK_GRAY}[-a|-p|-l|-t|-w|-f|-d|-h]${NOCOLOR}"
  echo -e "${BLUE}"
  echo "  -a - Upgrade everything"
  echo "  -p - Upgrade packages"
  echo "  -l - Upgrade fn-pc-apple"
  echo "  -t - Upgrade fn-pc-atari"
  echo "  -w - Upgrade AppleWin"
  echo "  -f - Upgrade tnfsd"
  echo "  -d - Upgrade dir2atr"
  echo "  -h - Print this help"
  echo -e "${NOCOLOR}"
  exit 1
}

function error() {
  echo -e "${RED}ERROR: ${YELLOW}$1${NOCOLOR}"
  usage
}

function message() {
  echo -e "${GREEN}${1}${NOCOLOR}"
}

function do_packages() {
  message "Upgrading packages ..."
  sudo apt update 
  sudo apt upgrade -y 
  sudo apt autoremove -y
}

function do_firmware_repo() {
  message "Updating fujinet-firmware ..."
  cd "$FUJINET_ROOT/fujinet-firmware"
  git pull --rebase
}

function do_pc_apple() {
  message "Upgrading fn-pc-apple ..."
  cd "$FUJINET_ROOT/fujinet-firmware"
  sudo systemctl stop fn-pc-apple
  ./build.sh -p APPLE 
  rsync -au "$HOME/FujiNet/fujinet-firmware/build/dist/" "$HOME/FujiNet/FujiNet-PC-Apple"
  sudo systemctl restart fn-pc-apple
}

function do_pc_atari() {
  message "Upgrading fn-pc-atari ..."
  cd "$FUJINET_ROOT/fujinet-firmware"
  sudo systemctl stop fn-pc-atari 
  ./build.sh -p ATARI 
  rsync -au "$HOME/FujiNet/fujinet-firmware/build/dist/" "$HOME/FujiNet/FujiNet-PC-Atari"
  sudo systemctl restart fn-pc-atari 
  sudo systemctl restart fn-emulator-bridge
}

function do_applewin() {
  message "Upgrade AppleWin ..."
  cd "$FUJINET_ROOT/AppleWin"
  git fetch --all 
  git pull --rebase 
  git submodule update --init --recursive 
  cd build
  cmake -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_SA2=on .. 
  make
  sudo make install 
}

function do_tnfsd() {
  message "Upgrade tnfsd ..."
  sudo curl -sLo /usr/local/sbin/tnfsd "https://fujinet.online/firmware/tnfsd.linux64"
  sudo chmod +x /usr/local/sbin/tnfsd 
  sudo systemctl restart tnfsd
}

function do_dir2atr() {
  message "Upgrade dir2atr ..."
  CODE_PATH="$FUJINET_ROOT/AtariSIO"
  git clone "https://github.com/HiassofT/AtariSIO.git" "$CODE_PATH"
  cd "$CODE_PATH/tools" || exit

  make -f Makefile.posix 
  sudo make -f Makefile.posix install 
}

while getopts ":pltwafd" opts
do
  case "$opts" in 
    p)
      do_packages 
      ;; 
    l)
      do_firmware_repo
      do_pc_apple 
      ;;
    t)
      do_firmware_repo
      do_pc_atari
      ;;
    w)
      do_applewin
      ;;
    f) 
      do_tnfsd 
      ;;
    d)
      do_dir2atr 
      ;;
    a)
      do_packages 
      do_firmware_repo 
      do_pc_apple
      do_pc_atari
      do_applewin
      do_tnfsd
      do_dir2atr
      ;;
    *) 
      usage 
      ;;
  esac
done
shift $(( OPTIND-1 ))
